server.port=8086

spring.datasource.url=jdbc:mysql://localhost:3312/nfce_db
spring.datasource.username=root
spring.datasource.password=gestex2026
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

focus.nfce.url.homologacao=https://homologacao.focusnfe.com.br/v2/nfce
focus.nfce.url.producao=https://api.focusnfe.com.br/v2/nfce
