server.port=${SERVER_PORT:8086}
server.address=0.0.0.0

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3312/nfce_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:gestex2026}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true

focus.nfce.url.homologacao=https://homologacao.focusnfe.com.br/v2/nfce
focus.nfce.url.producao=https://api.focusnfe.com.br/v2/nfce